"use client";
import React,{useState,useEffect,useRef}from"react";
import Link from"next/link";
import{createClient}from"@supabase/supabase-js";
const supabase=createClient(process.env.NEXT_PUBLIC_SUPABASE_URL,process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY);
const TECHNIQUES=[
{id:"coherence",name:"Coherence Breathing",bestFor:"HRV coherence, sustained presence",description:"5 in, 5 out. No holds. 6 breaths per minute � the frequency at which heart rate variability peaks. Primary HeartMath protocol.",phases:[{label:"Breathe in",duration:5},{label:"Breathe out",duration:5}],color:"212,160,60"},
{id:"box",name:"Box Breathing",bestFor:"Stress regulation, focus, reset",description:"4 in, hold 4, out 4, hold 4. Used by military and surgeons for rapid nervous system regulation under pressure.",phases:[{label:"Breathe in",duration:4},{label:"Hold",duration:4},{label:"Breathe out",duration:4},{label:"Hold",duration:4}],color:"193,68,14"},
{id:"478",name:"4-7-8 Breathing",bestFor:"Anxiety, sleep, deep release",description:"4 in, hold 7, out 8. Extended exhale activates the vagus nerve deeply. One of the most effective rapid anxiety relief techniques.",phases:[{label:"Breathe in",duration:4},{label:"Hold",duration:7},{label:"Breathe out",duration:8}],color:"150,100,200"},
{id:"extended",name:"Extended Exhale",bestFor:"Grounding, emotional regulation",description:"4 in, 8 out. Double-length exhale directly stimulates parasympathetic response. Simple, no holds required.",phases:[{label:"Breathe in",duration:4},{label:"Breathe out",duration:8}],color:"60,160,120"},
{id:"resonant",name:"Resonant Breathing",bestFor:"Deep presence, field transmission",description:"5 in, 5 out. Practiced with full awareness of each cycle as a complete field signal.",phases:[{label:"Breathe in",duration:5},{label:"Breathe out",duration:5}],color:"255,140,60"}
];
const PROMPTS=["Notice your chest. No need to change anything � just notice.","Feel the weight of your body against whatever is beneath you.","What is already here? Not what should be. What is.","You do not have to fix anything right now. You only have to feel it.","The field is not somewhere else. It is what you are standing in.","Presence is the only currency that matters here.","Whatever brought you here � this moment is enough.","The breath is always happening. You are just noticing it now."];
function useCoherence(active){const[v,setV]=useState(0.35);const t=useRef(0);useEffect(()=>{if(!active)return;const id=setInterval(()=>{t.current+=0.006;setV(Math.max(0.1,Math.min(1,0.52+Math.sin(t.current*0.22)*0.28+Math.sin(t.current*0.55)*0.1)));},50);return()=>clearInterval(id);},[active]);return v;}
function Pacer({phases,active,color}){const[pi,setPi]=useState(0);const[prog,setProg]=useState(0);const[scale,setScale]=useState(0.5);const ir=useRef(null);const fr=useRef(0);const sr=useRef(0);useEffect(()=>{if(!active){if(ir.current)clearTimeout(ir.current);cancelAnimationFrame(fr.current);setPi(0);setProg(0);setScale(0.5);return;}function run(p){setPi(p);const dur=phases[p].duration*1000;sr.current=performance.now();const lbl=phases[p].label.toLowerCase();const isIn=lbl.includes("in");const isOut=lbl.includes("out");function anim(now){const pr=Math.min((now-sr.current)/dur,1);setProg(pr);if(isIn)setScale(0.5+pr*0.5);else if(isOut)setScale(1-pr*0.5);else setScale(p===1?1:0.5);if(pr<1)fr.current=requestAnimationFrame(anim);else ir.current=setTimeout(()=>run((p+1)%phases.length),80);}fr.current=requestAnimationFrame(anim);}run(0);return()=>{if(ir.current)clearTimeout(ir.current);cancelAnimationFrame(fr.current);};},[active,phases]);const sz=220;const R=88;const circ=2*Math.PI*R;const c="rgba("+color+",";return(<div style={{display:"flex",flexDirection:"column",alignItems:"center",gap:"1rem",width:"100%"}}><div style={{position:"relative",width:sz,height:sz}}><svg width={sz} height={sz} style={{position:"absolute",inset:0}}><circle cx={sz/2} cy={sz/2} r={R} fill="none" stroke="rgba(232,221,208,0.08)" strokeWidth="1"/><circle cx={sz/2} cy={sz/2} r={R} fill="none" stroke={c+"0.85)"} strokeWidth="3" strokeDasharray={(circ*prog)+" "+circ} strokeLinecap="round" transform={"rotate(-90 "+(sz/2)+" "+(sz/2)+")"} style={{transition:"stroke-dasharray 0.05s linear"}}/></svg><div style={{position:"absolute",inset:0,display:"flex",alignItems:"center",justifyContent:"center"}}><div style={{width:100,height:100,borderRadius:"9999px",background:"radial-gradient(ellipse at center,"+c+"0.35) 0%,"+c+"0.1) 55%,transparent 75%)",transform:"scale("+scale+")",transition:"transform 0.08s ease",boxShadow:"0 0 "+(20+scale*40)+"px "+c+(0.15+scale*0.2)+")"}}/></div><div style={{position:"absolute",inset:0,display:"flex",flexDirection:"column",alignItems:"center",justifyContent:"center",gap:"0.2rem"}}>{active&&<><span style={{fontFamily:"Georgia,serif",fontSize:"clamp(2.2rem,5vw,3.5rem)",color:"rgba(232,221,208,0.85)",fontWeight:300,lineHeight:1}}>Math.max(1,Math.ceil(phases[pi].duration*(1-prog)))</span><span style={{fontFamily:"monospace",fontSize:"0.55rem",color:"rgba(232,221,208,0.4)",letterSpacing:"0.2em",textTransform:"uppercase"}}>sec</span></>}</div></div><p style={{fontFamily:"monospace",fontSize:"clamp(0.65rem,1.3vw,0.78rem)",letterSpacing:"0.28em",textTransform:"uppercase",color:active?c+"0.85)":"rgba(232,221,208,0.35)",transition:"color 0.5s ease",textAlign:"center",minHeight:"1.8rem"}}>{active?phases[pi].label:"Select a pattern below"}</p></div>);}
function Meter({v,active}){const pct=Math.round(v*100);return(<div style={{display:"flex",flexDirection:"column",alignItems:"center",gap:"0.5rem",opacity:active?1:0.25,transition:"opacity 1.5s ease"}}><div style={{display:"flex",alignItems:"center",gap:"0.6rem"}}><span className="animate-pulse" style={{display:"inline-block",width:"5px",height:"5px",borderRadius:"9999px",backgroundColor:"#FF6B3D",animationDuration:"2s"}}/><span style={{fontFamily:"monospace",fontSize:"clamp(0.52rem,1vw,0.62rem)",letterSpacing:"0.32em",textTransform:"uppercase",color:"rgba(232,221,208,0.55)"}}>Field coherence: live</span><span className="animate-pulse" style={{display:"inline-block",width:"5px",height:"5px",borderRadius:"9999px",backgroundColor:"#FF6B3D",animationDuration:"2s",animationDelay:"0.6s"}}/></div><div style={{display:"flex",alignItems:"center",gap:"0.75rem"}}><div style={{width:"clamp(8rem,18vw,14rem)",height:"2px",backgroundColor:"rgba(232,221,208,0.08)",borderRadius:"9999px",position:"relative",overflow:"hidden"}}><div style={{position:"absolute",left:0,top:0,height:"100%",width:pct+"%",background:"linear-gradient(to right,#6B1800,#C1440E,#FFB347)",transition:"width 1.2s ease",boxShadow:"0 0 12px rgba(255,179,71,"+(v*0.7)+")"}}/></div><span style={{fontFamily:"monospace",fontSize:"0.75rem",color:"rgba(212,136,74,0.85)",width:"2.8rem"}}>{pct}%</span></div></div>);}
function Feed(){const[sigs,setSigs]=useState([]);useEffect(()=>{supabase.from("signals").select("id,text").order("created_at",{ascending:false}).limit(6).then(({data})=>{if(data)setSigs(data);});const ch=supabase.channel("step-feed").on("postgres_changes",{event:"INSERT",schema:"public",table:"signals"},(p)=>{setSigs((prev)=>[{id:p.new.id,text:p.new.text},...prev].slice(0,6));}).subscribe();return()=>{supabase.removeChannel(ch);};},[]);if(sigs.length===0)return null;return(<div style={{position:"fixed",bottom:"2rem",left:"50%",transform:"translateX(-50%)",width:"min(500px,88vw)",zIndex:5,pointerEvents:"none"}}><p style={{fontFamily:"monospace",fontSize:"0.5rem",letterSpacing:"0.25em",textTransform:"uppercase",color:"rgba(212,160,60,0.3)",textAlign:"center",marginBottom:"0.5rem"}}>Others in the field now</p>{sigs.slice(0,3).map((s)=>(<p key={s.id} style={{fontFamily:"Georgia,serif",fontStyle:"italic",fontSize:"0.72rem",color:"rgba(232,221,208,0.18)",textAlign:"center",lineHeight:1.6,overflow:"hidden",whiteSpace:"nowrap",textOverflow:"ellipsis"}}>{s.text.length>60?s.text.slice(0,60)+"...":s.text}</p>))}</div>);}
function TechCard({t,selected,onSelect}){const isSelected=selected===t.id;function enter(e){if(!isSelected){e.currentTarget.style.borderColor="rgba("+t.color+",0.35)";e.currentTarget.style.backgroundColor="rgba(232,221,208,0.03)";}}function leave(e){if(!isSelected){e.currentTarget.style.borderColor="rgba(232,221,208,0.1)";e.currentTarget.style.backgroundColor="rgba(232,221,208,0.02)";}}return(<div onClick={()=>onSelect(t.id)} onMouseEnter={enter} onMouseLeave={leave} style={{width:"100%",padding:"clamp(0.85rem,2vh,1.1rem) 1.25rem",border:isSelected?"1px solid rgba("+t.color+",0.65)":"1px solid rgba(232,221,208,0.1)",backgroundColor:isSelected?"rgba("+t.color+",0.07)":"rgba(232,221,208,0.02)",cursor:"crosshair",transition:"all 0.3s ease",display:"flex",flexDirection:"column",gap:"0.3rem"}}><div style={{display:"flex",justifyContent:"space-between",alignItems:"center",flexWrap:"wrap",gap:"0.4rem"}}><span style={{fontFamily:"Georgia,serif",fontSize:"clamp(0.9rem,1.8vw,1.05rem)",color:isSelected?"rgba("+t.color+",0.95)":"rgba(232,221,208,0.78)",fontStyle:"italic",transition:"color 0.3s ease"}}>{t.name}</span><span style={{fontFamily:"monospace",fontSize:"0.58rem",letterSpacing:"0.18em",color:isSelected?"rgba("+t.color+",0.6)":"rgba(232,221,208,0.35)",transition:"color 0.3s ease"}}>{t.phases.map((p)=>p.duration).join("-")}</span></div><span style={{fontFamily:"monospace",fontSize:"clamp(0.58rem,1vw,0.65rem)",color:"rgba(232,221,208,0.45)",letterSpacing:"0.05em"}}>Best for: {t.bestFor}</span>{isSelected&&<span style={{fontFamily:"monospace",fontSize:"clamp(0.6rem,1.1vw,0.68rem)",lineHeight:1.9,color:"rgba(232,221,208,0.55)",marginTop:"0.4rem",letterSpacing:"0.03em",display:"block"}}>{t.description}</span>}</div>);}
export default function StepPage(){const[loaded,setLoaded]=useState(false);const[selected,setSelected]=useState(null);const[breathing,setBreathing]=useState(false);const[pi,setPi]=useState(0);const[pv,setPv]=useState(true);const[cycles,setCycles]=useState(0);const[elapsed,setElapsed]=useState(0);const[showTimer,setShowTimer]=useState(false);const coh=useCoherence(breathing);const tRef=useRef(null);const topRef=useRef(null);const tech=TECHNIQUES.find((t)=>t.id===selected);
useEffect(()=>{setTimeout(()=>setLoaded(true),200);},[]);
useEffect(()=>{if(!breathing){if(tRef.current)clearInterval(tRef.current);return;}setElapsed(0);tRef.current=setInterval(()=>setElapsed((e)=>e+1),1000);return()=>{if(tRef.current)clearInterval(tRef.current);};},[breathing]);
useEffect(()=>{if(!breathing)return;const id=setInterval(()=>{setPv(false);setTimeout(()=>{setPi((i)=>(i+1)%PROMPTS.length);setPv(true);setCycles((c)=>c+1);},1000);},20000);return()=>clearInterval(id);},[breathing]);
function select(id){if(selected===id){setBreathing((b)=>!b);if(breathing)setCycles(0);}else{setBreathing(false);setCycles(0);setSelected(id);setPi(0);setPv(true);setTimeout(()=>setBreathing(true),400);topRef.current&&topRef.current.scrollIntoView({behavior:"smooth",block:"start"});}}
function end(){setBreathing(false);setCycles(0);setSelected(null);setElapsed(0);}
const mm=Math.floor(elapsed/60).toString().padStart(2,"0");const ss=(elapsed%60).toString().padStart(2,"0");
return(<div style={{backgroundColor:"#090705",minHeight:"100vh",width:"100%",display:"flex",flexDirection:"column",alignItems:"center",position:"relative",overflowX:"hidden"}}><div aria-hidden="true" style={{position:"fixed",inset:0,pointerEvents:"none",zIndex:0,background:"radial-gradient(ellipse 80% 80% at 50% 40%,rgba(150,55,10,0.2) 0%,rgba(9,7,5,0) 65%)"}}/>{breathing&&<Feed/>}<div ref={topRef} style={{position:"relative",zIndex:10,width:"100%",maxWidth:"min(720px,94vw)",margin:"0 auto",padding:"clamp(2.5rem,6vh,4.5rem) 1.5rem clamp(5rem,12vh,9rem)",display:"flex",flexDirection:"column",alignItems:"center"}}>
<div style={{width:"100%",marginBottom:"clamp(1.5rem,4vh,2.5rem)",opacity:loaded?1:0,transition:"opacity 2s ease 0.2s",display:"flex",justifyContent:"space-between",alignItems:"center"}}><Link href="/" style={{fontFamily:"monospace",fontSize:"0.62rem",letterSpacing:"0.28em",textTransform:"uppercase",color:"rgba(212,160,60,0.55)",textDecoration:"none"}}>Back to the field</Link>{breathing&&<div style={{display:"flex",alignItems:"center",gap:"0.75rem"}}>{showTimer&&<span style={{fontFamily:"monospace",fontSize:"0.72rem",color:"rgba(232,221,208,0.45)",letterSpacing:"0.15em"}}>{mm}:{ss}</span>}<button onClick={()=>setShowTimer((v)=>!v)} style={{fontFamily:"monospace",fontSize:"0.55rem",letterSpacing:"0.2em",textTransform:"uppercase",color:"rgba(232,221,208,0.35)",background:"none",border:"none",cursor:"crosshair"}}>{showTimer?"hide":"timer"}</button></div>}</div>
<header style={{textAlign:"center",marginBottom:"clamp(1.5rem,4vh,2.5rem)",opacity:loaded?1:0,transition:"opacity 2s ease 0.4s"}}><p style={{fontFamily:"monospace",fontSize:"0.65rem",letterSpacing:"0.4em",textTransform:"uppercase",color:"rgba(212,160,60,0.5)",marginBottom:"1rem"}}>Resonant Earth</p><h1 style={{fontFamily:"Georgia,serif",fontWeight:300,fontSize:"clamp(1.8rem,5vw,3.2rem)",lineHeight:1.1,color:"rgba(232,221,208,0.92)",margin:0}}>Step Into the System</h1><div style={{width:"3rem",height:"1px",backgroundColor:"rgba(193,68,14,0.45)",margin:"1.5rem auto 0"}}/><p style={{fontFamily:"monospace",fontSize:"clamp(0.62rem,1.2vw,0.72rem)",lineHeight:1.9,color:"rgba(232,221,208,0.45)",letterSpacing:"0.04em",marginTop:"1.2rem",maxWidth:"460px",margin:"1.2rem auto 0"}}>Choose what resonates for you today. Each pattern works. None is required.</p></header>
<div style={{width:"100%",marginBottom:"clamp(1.5rem,3vh,2rem)",opacity:loaded?1:0,transition:"opacity 2s ease 0.5s"}}><Pacer phases={tech?tech.phases:[{label:"",duration:5},{label:"",duration:5}]} active={breathing} color={tech?tech.color:"232,221,208"}/></div>
<div style={{marginBottom:"clamp(1rem,2.5vh,1.8rem)",opacity:loaded?1:0,transition:"opacity 2s ease 0.6s"}}><Meter v={coh} active={breathing}/></div>
{breathing&&<div style={{textAlign:"center",maxWidth:"440px",minHeight:"3.5rem",display:"flex",alignItems:"center",justifyContent:"center",marginBottom:"clamp(1rem,2vh,1.5rem)"}}><p style={{fontFamily:"Georgia,serif",fontStyle:"italic",fontSize:"clamp(0.95rem,2.2vw,1.1rem)",lineHeight:1.85,color:"rgba(232,221,208,0.65)",opacity:pv?1:0,transition:"opacity 1s ease",textAlign:"center"}}>{PROMPTS[pi]}</p></div>}
{cycles>0&&<p style={{fontFamily:"monospace",fontSize:"0.58rem",color:"rgba(232,221,208,0.3)",letterSpacing:"0.2em",marginBottom:"0.75rem"}}>{cycles} {cycles===1?"cycle":"cycles"} complete</p>}
{breathing&&<button onClick={end} style={{padding:"0.65rem 2rem",border:"1px solid rgba(232,221,208,0.18)",backgroundColor:"transparent",color:"rgba(232,221,208,0.45)",fontFamily:"monospace",fontSize:"0.62rem",letterSpacing:"0.22em",textTransform:"uppercase",cursor:"crosshair",transition:"all 0.4s ease",marginBottom:"clamp(1.5rem,3vh,2rem)"}} onMouseEnter={(e)=>{e.currentTarget.style.borderColor="#C1440E";e.currentTarget.style.color="rgba(232,221,208,0.9)";}} onMouseLeave={(e)=>{e.currentTarget.style.borderColor="rgba(232,221,208,0.18)";e.currentTarget.style.color="rgba(232,221,208,0.45)";}}>End Practice</button>}
<div style={{width:"100%",display:"flex",flexDirection:"column",gap:"0.6rem",marginBottom:"clamp(2rem,5vh,3rem)",opacity:loaded?1:0,transition:"opacity 2s ease 0.7s"}}><p style={{fontFamily:"monospace",fontSize:"0.58rem",letterSpacing:"0.3em",textTransform:"uppercase",color:"rgba(212,160,60,0.45)",textAlign:"center",marginBottom:"0.4rem"}}>Choose your pattern</p>{TECHNIQUES.map((t)=>(<TechCard key={t.id} t={t} selected={selected} onSelect={select}/>))}</div>
<div style={{width:"100%",borderTop:"1px solid rgba(193,68,14,0.1)",paddingTop:"clamp(1.5rem,3vh,2.5rem)",opacity:loaded?1:0,transition:"opacity 2s ease 1.2s"}}><p style={{fontFamily:"monospace",fontSize:"clamp(0.52rem,1vw,0.62rem)",letterSpacing:"0.3em",textTransform:"uppercase",color:"rgba(212,160,60,0.35)",textAlign:"center",marginBottom:"1rem"}}>The science</p><p style={{fontFamily:"monospace",fontSize:"clamp(0.62rem,1.1vw,0.7rem)",lineHeight:2,color:"rgba(232,221,208,0.38)",letterSpacing:"0.03em",textAlign:"center",maxWidth:"520px",margin:"0 auto"}}>Each pattern activates the parasympathetic nervous system through the vagus nerve. The exhale phase is where coherence deepens. The 5-5 rhythm targets the 0.1 Hz frequency at which heart rate variability peaks, the measurable signature of a coherent field.</p></div>
<div style={{marginTop:"clamp(2.5rem,5vh,4rem)",textAlign:"center",opacity:loaded?1:0,transition:"opacity 2s ease 1.4s"}}><Link href="/" style={{display:"inline-block",padding:"0.75rem 2rem",border:"1px solid rgba(193,68,14,0.3)",backgroundColor:"transparent",color:"rgba(232,221,208,0.6)",fontFamily:"monospace",fontSize:"0.62rem",letterSpacing:"0.24em",textTransform:"uppercase",textDecoration:"none",cursor:"crosshair",transition:"all 0.4s ease"}} onMouseEnter={(e)=>{const el=e.currentTarget;el.style.backgroundColor="rgba(193,68,14,0.1)";el.style.borderColor="#C1440E";el.style.color="rgba(232,221,208,1)";}} onMouseLeave={(e)=>{const el=e.currentTarget;el.style.backgroundColor="transparent";el.style.borderColor="rgba(193,68,14,0.3)";el.style.color="rgba(232,221,208,0.6)";}}>Return to the Field</Link></div>
<footer style={{marginTop:"clamp(1.5rem,3vh,2.5rem)",textAlign:"center"}}><p style={{fontFamily:"monospace",fontSize:"0.5rem",color:"rgba(232,221,208,0.12)",letterSpacing:"0.2em"}}>Resonant Earth � A shared system for conscious results</p></footer>
</div></div>);}