"use client";
import React,{useState,useEffect,useRef}from"react";
import dynamic from"next/dynamic";
import Link from"next/link";
import{createClient}from"@supabase/supabase-js";

const supabase=createClient(process.env.NEXT_PUBLIC_SUPABASE_URL,process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY);
const FractalHeart=dynamic(()=>import("../components/FractalHeart"),{ssr:false});
const TRANSMISSIONS=["The old systems end when enough of us stop running them.","This is not a movement. It is a new way for presence to create collective results.","Sovereignty is always available. Everything else is optional.","The conscious economy begins where personal bypass ends.","You do not have to believe anything new. You just stop running the same loops.","Presence is the new leverage. Collective results are the new norm.","Whatever path brought you here, this is one place to build something different.","The field responds to presence."];

function useSimulatedCoherence(){const[coherence,setCoherence]=useState(0.4);const t=useRef(0);useEffect(()=>{const id=setInterval(()=>{t.current+=0.006;const v=0.48+Math.sin(t.current*0.22)*0.25+Math.sin(t.current*0.55)*0.1+Math.sin(t.current*1.1)*0.04;setCoherence(Math.max(0.1,Math.min(1,v)));},50);return()=>clearInterval(id);},[]);return coherence;}
function useTypewriter(text,speed=24){const[displayed,setDisplayed]=useState("");useEffect(()=>{setDisplayed("");let i=0;const id=setInterval(()=>{i++;setDisplayed(text.slice(0,i));if(i>=text.length)clearInterval(id);},speed);return()=>clearInterval(id);},[text,speed]);return displayed;}
function FieldDot({delay="0s"}){return React.createElement("span",{"aria-hidden":"true",className:"animate-pulse",style:{display:"inline-block",width:"5px",height:"5px",borderRadius:"9999px",backgroundColor:"#FF6B3D",animationDuration:"2.5s",animationDelay:delay,flexShrink:0}});}

function SignalForm({coherence}){const[text,setText]=useState("");const[focused,setFocused]=useState(false);const[status,setStatus]=useState("idle");const maxChars=320;async function handleTransmit(){if(!text.trim()||status==="sending")return;setStatus("sending");try{const{error}=await supabase.from("signals").insert({text:text.trim(),coherence:Math.round(coherence*1000)/1000});if(error)throw error;setStatus("success");setTimeout(()=>{setStatus("idle");setText("");},5000);}catch(err){console.error("Signal error:",err);setStatus("error");setTimeout(()=>setStatus("idle"),3000);}}
if(status==="success")return(<div style={{width:"100%",maxWidth:"min(520px,88vw)",textAlign:"center",padding:"2rem 1rem",display:"flex",flexDirection:"column",alignItems:"center",gap:"0.6rem"}}><p style={{fontFamily:"Georgia,serif",fontStyle:"italic",fontSize:"1rem",color:"rgba(212,160,60,0.9)",lineHeight:1.8}}>Signal transmitted to the field.</p><p style={{fontFamily:"monospace",fontSize:"0.6rem",color:"rgba(232,221,208,0.3)",letterSpacing:"0.2em",textTransform:"uppercase"}}>Individual presence � collective results.</p></div>);
return(<div style={{width:"100%",maxWidth:"min(520px,88vw)",display:"flex",flexDirection:"column",gap:"0.75rem",alignItems:"center"}}><p style={{fontFamily:"monospace",fontSize:"0.62rem",letterSpacing:"0.28em",textTransform:"uppercase",color:"rgba(212,160,60,0.55)",textAlign:"center"}}>What are you bringing into the field today?</p><div style={{width:"100%",position:"relative",border:focused?"1px solid rgba(193,68,14,0.6)":"1px solid rgba(232,221,208,0.08)",transition:"border-color 0.4s ease",backgroundColor:"rgba(232,221,208,0.02)"}}><textarea value={text} onChange={(e)=>setText(e.target.value.slice(0,maxChars))} onFocus={()=>setFocused(true)} onBlur={()=>setFocused(false)} placeholder="Speak honestly. This space holds what you bring." rows={4} style={{width:"100%",backgroundColor:"transparent",border:"none",outline:"none",resize:"none",padding:"1rem",fontFamily:"Georgia,serif",fontSize:"0.95rem",lineHeight:1.75,color:"rgba(232,221,208,0.78)",cursor:"crosshair"}} /><span style={{position:"absolute",bottom:"0.5rem",right:"0.75rem",fontFamily:"monospace",fontSize:"0.55rem",color:text.length>maxChars*0.85?"rgba(193,68,14,0.6)":"rgba(232,221,208,0.55)"}}>{maxChars-text.length}</span></div>{status==="error"&&<p style={{fontFamily:"monospace",fontSize:"0.58rem",color:"rgba(193,68,14,0.7)"}}>Signal could not be sent. Try again.</p>}<button onClick={handleTransmit} disabled={!text.trim()||status==="sending"} style={{alignSelf:"flex-end",padding:"0.65rem 1.8rem",border:text.trim()?"1px solid rgba(193,68,14,0.5)":"1px solid rgba(232,221,208,0.08)",backgroundColor:"transparent",color:text.trim()?"rgba(232,221,208,0.75)":"rgba(232,221,208,0.65)",fontFamily:"monospace",fontSize:"0.65rem",letterSpacing:"0.24em",textTransform:"uppercase",cursor:text.trim()?"crosshair":"default",transition:"all 0.4s ease"}} onMouseEnter={(e)=>{if(!text.trim())return;e.currentTarget.style.backgroundColor="rgba(193,68,14,0.12)";e.currentTarget.style.borderColor="#C1440E";e.currentTarget.style.color="rgba(232,221,208,1)";}} onMouseLeave={(e)=>{e.currentTarget.style.backgroundColor="transparent";e.currentTarget.style.borderColor=text.trim()?"rgba(193,68,14,0.5)":"rgba(232,221,208,0.08)";e.currentTarget.style.color=text.trim()?"rgba(232,221,208,0.75)":"rgba(232,221,208,0.65)";}}>
{status==="sending"?"Transmitting...":"Transmit"}</button></div>);}

function SignalFeed(){const[signals,setSignals]=useState([]);useEffect(()=>{async function load(){const{data}=await supabase.from("signals").select("id,text").order("created_at",{ascending:false}).limit(8);if(data)setSignals(data);}load();const channel=supabase.channel("signals-feed").on("postgres_changes",{event:"INSERT",schema:"public",table:"signals"},(payload)=>{setSignals((prev)=>[{id:payload.new.id,text:payload.new.text},...prev].slice(0,8));}).subscribe();return()=>{supabase.removeChannel(channel);};},[]);
if(signals.length===0)return null;
return(<div style={{width:"100%",maxWidth:"min(520px,88vw)",display:"flex",flexDirection:"column",gap:"0.5rem"}}><p style={{fontFamily:"monospace",fontSize:"0.6rem",letterSpacing:"0.28em",textTransform:"uppercase",color:"rgba(212,160,60,0.7)",textAlign:"center",marginBottom:"0.5rem"}}>Recent signals from the field</p>{signals.map((s)=>(<div key={s.id} style={{padding:"0.75rem 1rem",borderLeft:"1px solid rgba(193,68,14,0.18)",backgroundColor:"rgba(232,221,208,0.02)"}}><p style={{fontFamily:"Georgia,serif",fontStyle:"italic",fontSize:"0.88rem",lineHeight:1.7,color:"rgba(232,221,208,0.75)",margin:0}}>{s.text.length>120?s.text.slice(0,120)+"�":s.text}</p></div>))}</div>);}

function EmailForm(){const[email,setEmail]=useState("");const[focused,setFocused]=useState(false);const[status,setStatus]=useState("idle");async function handleSubmit(){if(!email.trim()||status==="sending")return;setStatus("sending");try{const{error}=await supabase.from("waitlist").insert({email:email.trim()});if(error)throw error;setStatus("success");}catch(err){console.error("Waitlist error:",err);setStatus("error");setTimeout(()=>setStatus("idle"),3000);}}
if(status==="success")return(<div style={{textAlign:"center",padding:"1rem"}}><p style={{fontFamily:"Georgia,serif",fontStyle:"italic",fontSize:"0.9rem",color:"rgba(212,160,60,0.8)"}}>You are in the field.</p><p style={{fontFamily:"monospace",fontSize:"0.58rem",color:"rgba(232,221,208,0.3)",letterSpacing:"0.15em",textTransform:"uppercase",marginTop:"0.4rem"}}>Updates will find you.</p></div>);
return(<div style={{width:"100%",maxWidth:"min(440px,88vw)",display:"flex",flexDirection:"column",gap:"0.6rem",alignItems:"center"}}><p style={{fontFamily:"monospace",fontSize:"0.6rem",letterSpacing:"0.28em",textTransform:"uppercase",color:"rgba(212,160,60,0.7)",textAlign:"center"}}>Get updates when the field opens more</p><div style={{width:"100%",display:"flex",gap:"0.5rem",flexWrap:"wrap",justifyContent:"center"}}><input type="email" value={email} onChange={(e)=>setEmail(e.target.value)} onFocus={()=>setFocused(true)} onBlur={()=>setFocused(false)} placeholder="your@email.com" style={{flex:1,minWidth:"200px",padding:"0.65rem 1rem",backgroundColor:"rgba(232,221,208,0.03)",border:focused?"1px solid rgba(193,68,14,0.5)":"1px solid rgba(232,221,208,0.08)",outline:"none",fontFamily:"monospace",fontSize:"0.72rem",color:"rgba(232,221,208,0.7)",transition:"border-color 0.3s ease",cursor:"crosshair"}} /><button onClick={handleSubmit} disabled={!email.trim()||status==="sending"} style={{padding:"0.65rem 1.4rem",border:email.trim()?"1px solid rgba(193,68,14,0.45)":"1px solid rgba(232,221,208,0.08)",backgroundColor:"transparent",color:email.trim()?"rgba(232,221,208,0.7)":"rgba(232,221,208,0.65)",fontFamily:"monospace",fontSize:"0.6rem",letterSpacing:"0.2em",textTransform:"uppercase",cursor:email.trim()?"crosshair":"default",transition:"all 0.3s ease",whiteSpace:"nowrap"}} onMouseEnter={(e)=>{if(!email.trim())return;e.currentTarget.style.backgroundColor="rgba(193,68,14,0.1)";e.currentTarget.style.borderColor="#C1440E";e.currentTarget.style.color="rgba(232,221,208,1)";}} onMouseLeave={(e)=>{e.currentTarget.style.backgroundColor="transparent";e.currentTarget.style.borderColor=email.trim()?"rgba(193,68,14,0.45)":"rgba(232,221,208,0.08)";e.currentTarget.style.color=email.trim()?"rgba(232,221,208,0.7)":"rgba(232,221,208,0.65)";}}>
{status==="sending"?"Joining...":"Join"}</button></div>{status==="error"&&<p style={{fontFamily:"monospace",fontSize:"0.56rem",color:"rgba(193,68,14,0.7)"}}>Could not join. Try again.</p>}<p style={{fontFamily:"monospace",fontSize:"0.52rem",color:"rgba(232,221,208,0.55)",textAlign:"center"}}>No spam. No pressure. On your own path.</p></div>);}

export default function HomePage(){const coherence=useSimulatedCoherence();const coherencePct=Math.round(coherence*100);const[txIndex,setTxIndex]=useState(0);const[txVisible,setTxVisible]=useState(true);const[txText,setTxText]=useState(TRANSMISSIONS[0]);const displayed=useTypewriter(txVisible?txText:"",24);const[hovered,setHovered]=useState(false);const mouseRef=useRef({x:0,y:0});const[heartOffset,setHeartOffset]=useState({x:0,y:0});const[earthOffset,setEarthOffset]=useState({x:0,y:0});const[loaded,setLoaded]=useState(false);
useEffect(()=>{const t=setTimeout(()=>setLoaded(true),200);return()=>clearTimeout(t);},[]);
useEffect(()=>{function onMove(e){mouseRef.current={x:(e.clientX/window.innerWidth-0.5)*2,y:(e.clientY/window.innerHeight-0.5)*2};}window.addEventListener("mousemove",onMove);return()=>window.removeEventListener("mousemove",onMove);},[]);
useEffect(()=>{let frameId;let hx=0,hy=0,ex=0,ey=0;function tick(){frameId=requestAnimationFrame(tick);const{x,y}=mouseRef.current;hx+=(-x*16-hx)*0.045;hy+=(-y*12-hy)*0.045;ex+=(x*6-ex)*0.018;ey+=(y*4-ey)*0.018;setHeartOffset({x:hx,y:hy});setEarthOffset({x:ex,y:ey});}tick();return()=>cancelAnimationFrame(frameId);},[]);
useEffect(()=>{const id=setInterval(()=>{setTxVisible(false);setTimeout(()=>{const next=(txIndex+1)%TRANSMISSIONS.length;setTxIndex(next);setTxText(TRANSMISSIONS[next]);setTxVisible(true);},1400);},14000);return()=>clearInterval(id);},[txIndex]);
return(<div style={{backgroundColor:"#090705",minHeight:"100vh",width:"100%",display:"flex",flexDirection:"column",alignItems:"center",justifyContent:"center",overflow:"hidden",position:"relative"}}>
<div aria-hidden="true" style={{position:"fixed",inset:0,pointerEvents:"none",zIndex:0,background:"radial-gradient(ellipse 90% 85% at 50% 46%, rgba(150,55,10,0.24) 0%, rgba(90,28,5,0.12) 38%, rgba(9,7,5,0) 68%)"}} />
<div style={{position:"relative",zIndex:10,width:"100%",maxWidth:"100vw",display:"flex",flexDirection:"column",alignItems:"center",padding:"clamp(2rem,5vh,5rem) 1rem clamp(2rem,4vh,4rem)"}}>
<p style={{fontFamily:"monospace",fontSize:"clamp(0.5rem,1.1vw,0.68rem)",letterSpacing:"0.12em",textTransform:"uppercase",color:"rgba(212,160,60,0.68)",marginBottom:"clamp(0.8rem,2vh,1.4rem)",textAlign:"center",maxWidth:"min(600px,88vw)",lineHeight:1.7,opacity:loaded?1:0,transition:"opacity 2.5s ease 0.3s"}}>A shared system where individual presence creates collective results � on your own path.</p>
<header style={{textAlign:"center",marginBottom:"clamp(0.8rem,2vh,1.5rem)",opacity:loaded?1:0,transition:"opacity 2.5s ease 0.5s"}}><div style={{position:"relative",display:"inline-block"}}><h1 style={{fontFamily:"Georgia,serif",fontWeight:300,lineHeight:1.0,position:"relative",margin:0}}><span style={{display:"block",fontSize:"clamp(3rem,10vw,8rem)",color:"rgba(222,188,75,0.9)",letterSpacing:"-0.01em"}}>Resonant</span><span style={{display:"block",fontSize:"clamp(3rem,10vw,8rem)",fontStyle:"italic",color:"rgba(193,68,14,0.95)",marginTop:"-0.12em",letterSpacing:"-0.01em"}}>Earth</span></h1></div></header>
<div style={{position:"relative",width:"min(640px,92vw)",height:"min(640px,92vw)",flexShrink:0,opacity:loaded?1:0,transition:"opacity 3s ease 0.8s"}} onMouseEnter={()=>setHovered(true)} onMouseLeave={()=>setHovered(false)}><div style={{position:"absolute",inset:0,transform:"translate("+heartOffset.x+"px,"+heartOffset.y+"px)",transition:"transform 0.06s linear"}}><FractalHeart coherence={coherence} className="w-full h-full" /></div></div>
<div style={{display:"flex",flexDirection:"column",alignItems:"center",gap:"0.55rem",marginTop:"clamp(1rem,2.5vh,2rem)",opacity:loaded?1:0,transition:"opacity 2s ease 1.4s"}}><div style={{display:"flex",alignItems:"center",gap:"0.5rem"}}><FieldDot /><span style={{color:"rgba(232,221,208,0.44)",fontFamily:"monospace",fontSize:"clamp(0.52rem,1vw,0.63rem)",letterSpacing:"0.32em",textTransform:"uppercase"}}>FIELD COHERENCE: LIVE</span><FieldDot delay="0.9s" /></div><div style={{display:"flex",alignItems:"center",gap:"0.85rem"}}><div style={{width:"clamp(7rem,15vw,12rem)",height:"1px",backgroundColor:"rgba(232,221,208,0.07)",borderRadius:"9999px",position:"relative",overflow:"hidden"}}><div style={{position:"absolute",left:0,top:0,height:"100%",width:coherencePct+"%",background:"linear-gradient(to right,#6B1800,#C1440E,#FFB347)",transition:"width 1.2s ease"}} /></div><span style={{color:"rgba(212,136,74,0.95)",fontFamily:"monospace",fontSize:"0.72rem",width:"2.8rem"}}>{coherencePct}%</span></div><p style={{color:"rgba(232,221,208,0.55)",fontFamily:"monospace",fontSize:"clamp(0.5rem,0.9vw,0.58rem)"}}>hover the heart � the field responds when presence is given</p></div>
<div style={{minHeight:"clamp(4rem,8vh,6rem)",maxWidth:"min(560px,88vw)",width:"100%",display:"flex",alignItems:"center",justifyContent:"center",textAlign:"center",margin:"clamp(1.5rem,4vh,3rem) 0 clamp(1rem,2.5vh,2rem)",opacity:loaded?1:0,transition:"opacity 2s ease 2s"}}><p style={{fontFamily:"Georgia,serif",fontStyle:"italic",fontSize:"clamp(0.95rem,2.4vw,1.22rem)",lineHeight:1.9,color:"rgba(232,221,208,0.58)",whiteSpace:"pre-line",opacity:txVisible?1:0,transition:"opacity 1.4s ease"}}>{displayed}{txVisible&&<span style={{opacity:0.28,fontStyle:"normal"}}>?</span>}</p></div>
<div style={{width:"100%",display:"flex",justifyContent:"center",marginBottom:"clamp(1rem,2vh,1.5rem)",opacity:loaded?1:0,transition:"opacity 2s ease 2.2s"}}><SignalForm coherence={coherence} /></div>
<div style={{width:"100%",display:"flex",justifyContent:"center",marginBottom:"clamp(1.5rem,3vh,2.5rem)",opacity:loaded?1:0,transition:"opacity 2s ease 2.4s"}}><SignalFeed /></div>
<div style={{display:"flex",gap:"clamp(0.5rem,2vw,1.2rem)",flexWrap:"wrap",justifyContent:"center",marginBottom:"clamp(2rem,4vh,3rem)",opacity:loaded?1:0,transition:"opacity 2s ease 2.5s"}}><Link href="/what-is-this" style={{padding:"clamp(0.7rem,1.5vh,0.9rem) clamp(1.4rem,3vw,2.4rem)",border:"1px solid rgba(193,68,14,0.4)",backgroundColor:"transparent",color:"rgba(232,221,208,0.72)",fontFamily:"monospace",fontSize:"clamp(0.58rem,1.1vw,0.68rem)",letterSpacing:"0.24em",textTransform:"uppercase",cursor:"crosshair",transition:"all 0.4s ease",textDecoration:"none",display:"inline-block"}} onMouseEnter={(e)=>{const el=e.currentTarget;el.style.backgroundColor="rgba(193,68,14,0.13)";el.style.borderColor="#C1440E";el.style.color="rgba(232,221,208,1)";}} onMouseLeave={(e)=>{const el=e.currentTarget;el.style.backgroundColor="transparent";el.style.borderColor="rgba(193,68,14,0.4)";el.style.color="rgba(232,221,208,0.72)";}}>What Is This?</Link><a href="/step-into-the-system" style={{padding:"clamp(0.7rem,1.5vh,0.9rem) clamp(1.4rem,3vw,2.4rem)",border:"1px solid rgba(193,68,14,0.4)",backgroundColor:"transparent",color:"rgba(232,221,208,0.72)",fontFamily:"monospace",fontSize:"clamp(0.58rem,1.1vw,0.68rem)",letterSpacing:"0.24em",textTransform:"uppercase",cursor:"crosshair",transition:"all 0.4s ease",textDecoration:"none",display:"inline-block",marginLeft:"clamp(0.5rem,2vw,1.2rem)"}} onMouseEnter={(e)=>{const el=e.currentTarget;el.style.backgroundColor="rgba(193,68,14,0.13)";el.style.borderColor="#C1440E";el.style.color="rgba(232,221,208,1)";}} onMouseLeave={(e)=>{const el=e.currentTarget;el.style.backgroundColor="transparent";el.style.borderColor="rgba(193,68,14,0.4)";el.style.color="rgba(232,221,208,0.72)";}}>Step Into the System</a></div>
<div style={{width:"100%",display:"flex",justifyContent:"center",marginBottom:"clamp(2rem,5vh,4rem)",opacity:loaded?1:0,transition:"opacity 2s ease 2.7s"}}><EmailForm /></div>
<footer style={{width:"100%",borderTop:"1px solid rgba(193,68,14,0.09)",padding:"clamp(1.5rem,4vh,2.8rem) 1rem",textAlign:"center"}}><div style={{maxWidth:"min(620px,90vw)",margin:"0 auto",display:"flex",flexDirection:"column",gap:"clamp(0.6rem,1.5vh,1rem)"}}><p style={{color:"rgba(212,136,74,0.9)",fontFamily:"monospace",fontSize:"clamp(0.52rem,0.95vw,0.62rem)",letterSpacing:"0.32em",textTransform:"uppercase"}}>Resonant Earth � A shared system for conscious results</p><p style={{color:"rgba(232,221,208,0.65)",fontFamily:"monospace",fontSize:"clamp(0.52rem,0.95vw,0.62rem)",lineHeight:2.1}}>This is not a wellness platform. This is not a spiritual bypass.<br/>It offers a space where presence can meet what is already here.</p><p style={{color:"rgba(232,221,208,0.55)",fontFamily:"monospace",fontSize:"clamp(0.48rem,0.88vw,0.58rem)",lineHeight:1.95}}>Resonant Earth offers a new way for presence to create collective results � on your own path.</p><div style={{display:"flex",alignItems:"center",justifyContent:"center",gap:"0.5rem",paddingTop:"0.4rem"}}><FieldDot /><span style={{color:"rgba(232,221,208,0.5)",fontFamily:"monospace",fontSize:"0.52rem"}}>field coherence: live � through your own presence</span><FieldDot delay="0.5s" /></div></div></footer>
</div></div>);}