"use client";
import React,{useState,useEffect}from"react";
import Link from"next/link";
export default function TermsPage(){const[loaded,setLoaded]=useState(false);useEffect(()=>{setTimeout(()=>setLoaded(true),200);},[]);
const sections=[{title:"The System",body:"Resonant Earth is a shared system where individual presence creates collective results � on your own path. It is owned in perpetuity by the South Dakota Perpetual Purpose Trust and operated by ECO Conscious LLC. Kyle Gencarelli is the temporary human antenna. By using Resonant Earth you agree to these Terms."},{title:"What You Can Do",body:"Send one honest signal (up to 320 characters). View the public feed and globe. Use the breath techniques on the Step Into the System page. Join the waitlist. Make a voluntary contribution. There are no accounts, no logins, and no profiles."},{title:"Your Signals Are Public",body:"When you submit a signal, the text becomes part of the public field. It appears in the live feed and triggers a pulse on the globe. Anyone on the internet can see it. No name or email is attached. By sending a signal you accept that it is visible to the world. Send only what you are willing to share."},{title:"License You Grant Us",body:"You grant Resonant Earth and the Trust a perpetual, worldwide, royalty-free, irrevocable license to display, reproduce, and transmit your signal text as part of the living field. You keep ownership of your words."},{title:"What You Agree Not to Do",body:"You will not not send signals that are illegal, hateful, harassing, violent, sexually explicit, or that infringe anyone else rights. We may remove any signal that violates these rules without notice."},{title:"Contributions",body:"Contributions are voluntary and flow directly to the Creation and Relief Funds governed by the Trust. All contributions are non-refundable. Stripe processes payments. We never see your card data."},{title:"No Promises",body:"The site is provided as is. We do not guarantee uptime, accuracy of the globe, coherence meter, or any outcome from using the system. This is not therapy, not financial advice, not a safety net, and not a replacement for professional help. Use it on your own path and at your own risk."},{title:"Limitation of Liability",body:"To the fullest extent permitted by law, Resonant Earth, the Trust, the LLC, and the operator are not liable for any indirect, incidental, or consequential damages arising from your use of the site."},{title:"Governing Law",body:"These Terms are governed by the laws of South Dakota, without regard to conflict of laws rules. Any disputes will be resolved in the courts of South Dakota."},{title:"Changes",body:"We may update these Terms. Continued use after changes means you accept them. We will update the effective date at the top."},{title:"Contact",body:"Email the operator at gencarellikyle@gmail.com."}];return(<div style={{backgroundColor:"#090705",minHeight:"100vh",width:"100%",position:"relative",overflowX:"hidden"}}>
<div aria-hidden="true" style={{position:"fixed",inset:0,pointerEvents:"none",zIndex:0,background:"radial-gradient(ellipse 80% 80% at 50% 40%,rgba(150,55,10,0.12) 0%,rgba(9,7,5,0) 65%)"}}/>
<div style={{position:"relative",zIndex:10,width:"100%",maxWidth:"min(720px,92vw)",margin:"0 auto",padding:"clamp(5rem,10vh,8rem) 1.5rem clamp(3rem,8vh,6rem)"}}>
<Link href="/" style={{display:"block",fontFamily:"monospace",fontSize:"0.6rem",letterSpacing:"0.28em",textTransform:"uppercase",color:"rgba(212,160,60,0.75)",textDecoration:"none",marginBottom:"clamp(2rem,5vh,4rem)"}}>Back to the field</Link>
<header style={{marginBottom:"clamp(2rem,5vh,4rem)",opacity:loaded?1:0,transition:"opacity 2s ease 0.3s"}}>
<p style={{fontFamily:"monospace",fontSize:"0.65rem",letterSpacing:"0.4em",textTransform:"uppercase",color:"rgba(212,160,60,0.75)",marginBottom:"0.75rem"}}>Resonant Earth</p>
<h1 style={{fontFamily:"Georgia,serif",fontWeight:300,fontSize:"clamp(2rem,5vw,3.5rem)",color:"rgba(232,221,208,0.88)",margin:0,marginBottom:"0.5rem"}}>Terms of Service</h1>
<p style={{fontFamily:"monospace",fontSize:"0.6rem",color:"rgba(232,221,208,0.35)",letterSpacing:"0.1em"}}>Effective Date: March 2026</p>
<div style={{width:"3rem",height:"1px",backgroundColor:"rgba(193,68,14,0.4)",marginTop:"1.5rem"}}/>
</header>
<div style={{display:"flex",flexDirection:"column",gap:"2.5rem",opacity:loaded?1:0,transition:"opacity 2s ease 0.6s"}}>
{sections.map((s,i)=>(<div key={i} style={{borderLeft:"1px solid rgba(193,68,14,0.2)",paddingLeft:"clamp(1rem,3vw,2rem)"}}>
<h2 style={{fontFamily:"Georgia,serif",fontWeight:300,fontSize:"clamp(1rem,2.2vw,1.2rem)",color:"rgba(222,188,75,0.85)",marginBottom:"0.75rem",fontStyle:"italic"}}>{s.title}</h2>
<p style={{fontFamily:"monospace",fontSize:"clamp(0.68rem,1.3vw,0.78rem)",lineHeight:2,color:"rgba(232,221,208,0.72)",letterSpacing:"0.03em"}}>{s.body}</p>
</div>))}
</div>
<div style={{marginTop:"3rem",borderTop:"1px solid rgba(193,68,14,0.12)",paddingTop:"2rem",opacity:loaded?1:0,transition:"opacity 2s ease 2s"}}>
<Link href="/" style={{display:"inline-block",padding:"0.75rem 2rem",border:"1px solid rgba(193,68,14,0.35)",backgroundColor:"transparent",color:"rgba(232,221,208,0.65)",fontFamily:"monospace",fontSize:"0.65rem",letterSpacing:"0.24em",textTransform:"uppercase",textDecoration:"none",cursor:"crosshair"}}>Return to the Field</Link>
</div>
</div></div>);}